### PR TITLE
Fix missing i18n path configuration

### PR DESCRIPTION
**Pull request by Tenchi2xh**

### CODE REVIEW

**Comment by mdvanes** [comment]
I don't think this will work, because the environmental variable will exist server side and this code is client side. Instead, it would have to be replaced in the build step.

**Comment by Tenchi2xh** [comment]
Didn't think about that, so I looked into it, apparently it could work.

[This](https://github.com/code-star/codestar-website-react/tree/develop#adding-assets-outside-of-the-module-system) says that the static `%PUBLIC_URL%` are substituted even client-side, and then say that `process.env.PUBLIC_URL` acts the same for the JS side.

I still wasn't convinced by that but then I read [this](https://github.com/facebook/create-react-app/issues/956#issuecomment-256013127) comment on an issue:

> > Thanks. It's a bit surprising that what looks like a node.js process environment variable is available on the client.

> It's a very common practice called "envifying".

> > What does 'process.env' represent, logically? A snapshot of what the node.js process environment was when webpack ran?

> Yes.

Apparently, it will capture this:

```json
  "homepage": "http://www.codestar.nl/codestar-website-react"
```

from our `package.json` as that `PUBLIC_URL` variable.

Should we try?

**Comment by mdvanes** [comment]
Ah ok, it works because of magic. Sure lets merge it in.

**Comment by Tenchi2xh** [comment]
It worked :)

**Pull request merged**
